/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as NewsRouteImport } from './routes/news'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagesRouterWeatherRouteImport } from './routes/pages-router.weather'
import { Route as PagesRouterSimpleRouteImport } from './routes/pages-router.simple'
import { Route as PagesRouterNewsRouteImport } from './routes/pages-router.news'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRouterWeatherRoute = PagesRouterWeatherRouteImport.update({
  id: '/pages-router/weather',
  path: '/pages-router/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRouterSimpleRoute = PagesRouterSimpleRouteImport.update({
  id: '/pages-router/simple',
  path: '/pages-router/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRouterNewsRoute = PagesRouterNewsRouteImport.update({
  id: '/pages-router/news',
  path: '/pages-router/news',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/simple': typeof SimpleRoute
  '/weather': typeof WeatherRoute
  '/pages-router/news': typeof PagesRouterNewsRoute
  '/pages-router/simple': typeof PagesRouterSimpleRoute
  '/pages-router/weather': typeof PagesRouterWeatherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/simple': typeof SimpleRoute
  '/weather': typeof WeatherRoute
  '/pages-router/news': typeof PagesRouterNewsRoute
  '/pages-router/simple': typeof PagesRouterSimpleRoute
  '/pages-router/weather': typeof PagesRouterWeatherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/news': typeof NewsRoute
  '/simple': typeof SimpleRoute
  '/weather': typeof WeatherRoute
  '/pages-router/news': typeof PagesRouterNewsRoute
  '/pages-router/simple': typeof PagesRouterSimpleRoute
  '/pages-router/weather': typeof PagesRouterWeatherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/news'
    | '/simple'
    | '/weather'
    | '/pages-router/news'
    | '/pages-router/simple'
    | '/pages-router/weather'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/news'
    | '/simple'
    | '/weather'
    | '/pages-router/news'
    | '/pages-router/simple'
    | '/pages-router/weather'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/news'
    | '/simple'
    | '/weather'
    | '/pages-router/news'
    | '/pages-router/simple'
    | '/pages-router/weather'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  NewsRoute: typeof NewsRoute
  SimpleRoute: typeof SimpleRoute
  WeatherRoute: typeof WeatherRoute
  PagesRouterNewsRoute: typeof PagesRouterNewsRoute
  PagesRouterSimpleRoute: typeof PagesRouterSimpleRoute
  PagesRouterWeatherRoute: typeof PagesRouterWeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-router/weather': {
      id: '/pages-router/weather'
      path: '/pages-router/weather'
      fullPath: '/pages-router/weather'
      preLoaderRoute: typeof PagesRouterWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-router/simple': {
      id: '/pages-router/simple'
      path: '/pages-router/simple'
      fullPath: '/pages-router/simple'
      preLoaderRoute: typeof PagesRouterSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages-router/news': {
      id: '/pages-router/news'
      path: '/pages-router/news'
      fullPath: '/pages-router/news'
      preLoaderRoute: typeof PagesRouterNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  NewsRoute: NewsRoute,
  SimpleRoute: SimpleRoute,
  WeatherRoute: WeatherRoute,
  PagesRouterNewsRoute: PagesRouterNewsRoute,
  PagesRouterSimpleRoute: PagesRouterSimpleRoute,
  PagesRouterWeatherRoute: PagesRouterWeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
